const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "94740061678"
const SESSION_ID = "PRABATH-MD~Re1mXQrC#Pz1G1y3rgAKDin_man-5pxWdXkgP2Xm0ebus1nmTwV4"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
